name: Deploy to Tomcat

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Stop Tomcat
        env:
          DEPLOY_SERVER: ${{ secrets.SERVER_IP }}
          DEPLOY_USER: ${{ secrets.SERVER_USERNAME }}
          DEPLOY_PATH: ${{ secrets.SERVER_PATH }}
        run: |
          ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER << EOF
          # Stop Tomcat
          ${DEPLOY_PATH}/bin/shutdown.sh
          EOF

      - name: Upload WAR file
        env:
          DEPLOY_SERVER: ${{ secrets.SERVER_IP }}
          DEPLOY_USER: ${{ secrets.SERVER_USERNAME }}
          DEPLOY_PATH: ${{ secrets.SERVER_PATH }}
        run: |
          scp -o StrictHostKeyChecking=no target/*.war $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH/webapps/

      - name: Start Tomcat
        env:
          DEPLOY_SERVER: ${{ secrets.SERVER_IP }}
          DEPLOY_USER: ${{ secrets.SERVER_USERNAME }}
          DEPLOY_PATH: ${{ secrets.SERVER_PATH }}
        run: |
          ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER << EOF
          # Wait for a few seconds before starting Tomcat
          sleep 10
          
          # Set JAVA_OPTS to include the JVM parameter
          export JAVA_OPTS="-Dspring.profiles.active=prod"
          
          # Start Tomcat
          ${DEPLOY_PATH}/bin/startup.sh
          EOF
